services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=event_tracker_db'
      - 'POSTGRES_PASSWORD=0na93rF6WB'
      - 'POSTGRES_USER=EventAdmin'
    ports:
      - '5250:5432'
    volumes:
      - pgdata:/var/lib/postgresql
volumes:
  pgdata:
